# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Global dependencies
    deps.fabric_loader=0.18.4

# Stonecutter
    mod.version=0.0.8-dev24
    mod.group=xyz.crazyh
    mod.id=fabrictweaker
    mod.name=FabricTweaker

# Mod Properties - old
	mod_version = 0.0.8-dev24
	maven_group = xyz.crazyh
	archives_base_name = FabricTweaker
