name: Java CI

on:
  push:
    branches:
      - multi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          echo "Commit: ${{ github.sha }}"
          echo "Build Time: $(date '+%Y-%m-%d %H:%M:%S')"
          ./gradlew buildAndCollect
      - uses: actions/upload-artifact@v4
        with:
          name: "FabricTweaker-${{ github.sha | slice: 0, 7 }}-${{ github.event.head_commit.timestamp | slice: 0, 10 }}"
          path: build/libs/
