name: Java CI

on:
  push:
    branches:
      - multi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          echo "Commit: ${{ github.sha }}"
          echo "Build Time: $(date '+%Y-%m-%d %H:%M:%S')"
          ./gradlew buildAndCollect
      - name: Set artifact name
        id: artifact-name
        run: echo "name=FabricTweaker-$(git rev-parse --short HEAD)-$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: build/libs/
